### ISSUE TITLE
how to change AUTO CLEAR???

### ISSUE THREAD

**Issue by Acool79** [ElMargaritox/EssentialsX-Documentation#1]
it spams chat and clears items every 60 seconds how do i turn off ??

**Comment by Shalitax** [comment]
Hi, check this line in **EssentialsX.configuration.xml** file

> AutoClearConfig Time_Barricades="300" Time_Items="1800" Enabled="false" Enabled_Messages="true" Vehicles="false" Time_Vehicles="300" Structures="false" Time_Structures="300" Barricades="false" Items="true

Change **Enabled="true"** to **Enabled="false"**

**Comment by Acool79** [comment]
Thanks you so much!!!!! 
/
home
/
[container](https://panel.pinehosting.com/server/2f73cbfc/files)
/
[Servers](https://panel.pinehosting.com/server/2f73cbfc/files#/Servers)
/
[unturned](https://panel.pinehosting.com/server/2f73cbfc/files#/Servers/unturned)
/
[Rocket](https://panel.pinehosting.com/server/2f73cbfc/files#/Servers/unturned/Rocket)
/
[Plugins](https://panel.pinehosting.com/server/2f73cbfc/files#/Servers/unturned/Rocket/Plugins)
/
[EssentialsX](https://panel.pinehosting.com/server/2f73cbfc/files#/Servers/unturned/Rocket/Plugins/EssentialsX)
/
EssentialsX.configuration.xml

is the file location if anyone needs to find it. Thank you so much shalitax!
